### ISSUE TITLE
Unable to install requirements

### ISSUE THREAD

**Issue by oneEyedSunday** [shalvah/TheCensorshipAPI#5]
I'm looking to try my hands at some Laravel, looking at issue #4. 
I can't get the project running cos you are using a [fork of](https://github.com/shalvah/TheCensorshipAPI/blob/8a584eb523b956640e34790b75560949838732de/composer.json#L13) `mpociot/laravel-apidoc-generator` that I do not know how to get. Could you add some instructions in the README for us prodigal php folks who don't know how to hack composer?

**Comment by shalvah** [comment]
Lol. This project was intended to be a fun little nonsensical project specifically to test features of mpociot/laravel-apidoc-generator (hence the link to my local copy of the package) (and also to keep my hands dirty in the Laravel world). I plan to add a README and perhaps open it for collaboration, but you'll have to wait a bit.

**Comment by shalvah** [comment]
But for the time being, you can delete the whole of the `repositories` section (https://github.com/shalvah/TheCensorshipAPI/blob/8a584eb523b956640e34790b75560949838732de/composer.json#L10-L18). I don't advise you committing anything yet, though. I've got some stuff on my local I haven't pushed yet.

**Comment by oneEyedSunday** [comment]
Aii man.
